### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by Arthuuurr** [MithrandirCraft/SimpleHubParkour#1]
To be able to put more than one parkour around the world and define the world where you want parkour

**Comment by Mangonels** [comment]
I'm sorry, but this plugin was designed to be "simple". And that means the word in it's full definition. It has a very limited scope.

It's also called "hub parkour", because there's only meant to be one track. That's just how this plugin is, for more complex solutions (like building an entire parkour server or whatever), go for a more complex plugin.
